# Generated by Django 3.0.8 on 2021-03-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0003_enrollcource_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent', models.DateTimeField(auto_now=True)),
                ('recipient', models.ManyToManyField(related_name='recipient', to='universystem.Profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='universystem.Profile')),
            ],
        ),
    ]
