# Generated by Django 3.0.8 on 2021-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0007_remove_lesson_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
