# Generated by Django 3.0.8 on 2021-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0009_auto_20210309_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
