# Generated by Django 3.0.8 on 2021-03-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0011_auto_20210321_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
