# Generated by Django 3.0.8 on 2021-04-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0014_delete_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lectures_text', models.TextField(blank=True, null=True)),
                ('lectures_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universystem.Lectures')),
            ],
        ),
    ]
