# Generated by Django 3.0.8 on 2021-04-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0017_lectures_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='value',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
