# Generated by Django 3.0.8 on 2021-04-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0020_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='video',
        ),
        migrations.AddField(
            model_name='lab',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos', verbose_name='videofile'),
        ),
    ]
