# Generated by Django 3.0.8 on 2021-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0021_auto_20210409_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='videofile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
