# Generated by Django 3.2.7 on 2022-03-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0022_auto_20210418_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
