# Generated by Django 3.2.7 on 2022-03-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0023_lectures_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lectures_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universystem.lectures_text')),
            ],
        ),
    ]
