# Generated by Django 3.2.7 on 2022-03-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0025_auto_20220304_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Cod',
        ),
        migrations.RenameField(
            model_name='cod',
            old_name='code',
            new_name='cod',
        ),
    ]
