# Generated by Django 3.2.7 on 2022-03-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0026_auto_20220304_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures_text',
            name='code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
