# Generated by Django 3.2.7 on 2022-03-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0027_lectures_text_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cod',
        ),
    ]
