# Generated by Django 3.2.7 on 2022-03-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0028_delete_cod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectures_text',
            old_name='code',
            new_name='lectures_cod',
        ),
    ]
