# Generated by Django 3.2.7 on 2022-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0030_alter_lectures_text_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures_text',
            name='lectures_cod',
            field=models.TextField(blank=True, null=True),
        ),
    ]
