# Generated by Django 3.2.7 on 2022-03-05 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universystem', '0031_alter_lectures_text_lectures_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollCource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('lectures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universystem.lectures')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
