# Generated by Django 3.2.7 on 2022-03-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0032_enrollcource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
