# Generated by Django 4.1.7 on 2023-05-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0033_auto_20220305_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Тестер қосу',
                'verbose_name_plural': 'Тестер қосу',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universystem.questionone')),
            ],
            options={
                'verbose_name': 'Тестің жауаптарын қосу',
                'verbose_name_plural': 'Тестің жауаптарын қосу',
            },
        ),
    ]
