# Generated by Django 4.1.7 on 2023-05-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0034_questionone_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'техникалық көмек',
                'verbose_name_plural': 'техникалық көмек',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
