# Generated by Django 4.0 on 2024-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0037_alter_lesson_document_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
